### ISSUE TITLE
Possible solution to fix ci pipeline

### ISSUE THREAD

**Issue by imblowfish** [golxzn/resman#1]
Hello, looks like you try to run the specific OS steps based on `matrix.os` interpolation,  but what if you'll try to change your solution  with `if` statement?

As example with the following code in the your ci file:

```yaml
    steps: 
       - uses: actions/checkout@v2 
  
       - name: Configure 
         shell: pwsh 
         run: cmake "--preset=ci-${{ env.platform }}" --fresh 
  
       - name: Build 
         run: cmake --build "--preset=${{ env.platform }}-build" 
  
       - name: Install 
         run: cmake --install "build/ci-${{ env.platform }}" --config ${{ env.BUILD_TYPE }} --prefix prefix 
  
       - name: Test 
         working-directory: $build/ci-${{ env.platform }}/code/tests 
         run: ctest "--preset=ci-${{ env.platform }}-test"
```

You can separate `Configure` and `Build` to Windows as follows:

```yaml
    steps: 
       - uses: actions/checkout@v2 
  
       - name: Configure Windows
         if: ${{ runner.os == "Windows"}} 
         shell: pwsh 
         run: cmake "--preset=ci-windows"--fresh 
  
       - name: Build Windows
         if: ${{ runner.os == "Windows"}} 
         run: cmake --build "--preset=windows-build" 
  
       - name: Install Windows
         if: ${{ runner.os == "Windows"}} 
         run: cmake --install "build/ci-windows" --config ${{ env.BUILD_TYPE }} --prefix prefix 
  
       - name: Test Windows
         working-directory: $build/ci-${{ env.platform }}/code/tests 
         run: ctest "--preset=ci-windows-test"
```

In result ci pipeline will use builtin actions' properties instead of custom strings' based solution

More info about if expressions https://docs.github.com/en/actions/learn-github-actions/expressions
More info about runner context https://docs.github.com/en/actions/learn-github-actions/contexts#runner-context

Hope this helps
